### PR TITLE
In creating a new password after password recover, ensure that the UI…

### LINKED ISSUE #1228: [Bug] Reset password does not check for repeated password
**Describe the bug**
When resetting password via forgotten password, the check for repeated password seems not enforced. It seems to just take "New password" inputted.

**To Reproduce**
Reset a password via forgotten password, getting token via email.

**Expected behavior**
Validation of the form in some way to make sure New passwords and repeated new password match before accepting new password.

**Screenshots**

image

**Details**
 - Version 4.4.0

### PR DESCRIPTION
**Pull request by bartvanb**
Fix #1228

### CODE REVIEW

**Review by frankcorneliusmartin — APPROVED** [review]
Also tested this and it works as expected

**Review by lsago — CHANGES_REQUESTED** [review]
Angular is definitely outside my wheelhouse :)
But, in trying to test, this fails to build for me:
```
$ git checkout bugfix/ui/validate-repeated-password-in-password-recover
$ make TAG=local REGISTRY=localhost:5055 PLATFORMS=linux/amd64 ui-image 
Building localhost:5055/infrastructure/ui:local
docker buildx build \
        --tag localhost:5055/infrastructure/ui:local \
        --tag localhost:5055/infrastructure/ui:latest \
        --build-arg TAG=local \
        --build-arg BASE=4.0 \
        --platform linux/amd64 \
        -f ./docker/ui.Dockerfile \
        .
[+] Building 39.8s (11/15)                                                                                                                                                                                                                                     docker:default
 => [internal] load build definition from ui.Dockerfile                                                                                                                                                                                                                  0.0s
 => => transferring dockerfile: 768B                                                                                                                                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/node:20-alpine                                                                                                                                                                                                        0.4s
 => [internal] load .dockerignore                                                                                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                          0.0s
 => [internal] load build context                                                                                                                                                                                                                                        0.0s
 => => transferring context: 34.83kB                                                                                                                                                                                                                                     0.0s
 => [stage-1 1/5] FROM docker.io/library/nginx:alpine                                                                                                                                                                                                                    0.0s
 => [node 1/5] FROM docker.io/library/node:20-alpine@sha256:291e84d956f1aff38454bbd3da38941461ad569a185c20aa289f71f37ea08e23                                                                                                                                             0.0s
 => CACHED [node 2/5] WORKDIR /app                                                                                                                                                                                                                                       0.0s
 => CACHED [node 3/5] COPY vantage6-ui/ /app                                                                                                                                                                                                                             0.0s
 => CACHED [node 4/5] RUN npm install                                                                                                                                                                                                                                    0.0s
 => ERROR [node 5/5] RUN npm run build                                                                                                                                                                                                                                  39.0s
------                                                                                                                                                                                                                                                                        
 > [node 5/5] RUN npm run build:                                                                                                                                                                                                                                              
0.373                                                                                                                                                                                                                                                                         
0.373 > vantage6-UI@4.4.0 build                                                                                                                                                                                                                                               
0.373 > ng build                                                                                                                                                                                                                                                              
0.373                                                                                                                                                                                                                                                                         
1.448 - Generating browser application bundles (phase: setup)...
37.61 ✔ Browser application bundle generation complete.
38.42 ✔ Browser application bundle generation complete.
38.42 
38.42 Warning: /app/node_modules/angularx-qrcode/fesm2022/angularx-qrcode.mjs depends on 'qrcode'. CommonJS or AMD dependencies can cause optimization bailouts.
38.42 For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
38.42 
38.42 Warning: /app/src/app/layouts/layout-default/layout-default.component.scss exceeded maximum budget. Budget 2.00 kB was not met by 84.16 kB with a total of 86.16 kB.
38.42 
38.42 Warning: /app/src/app/services/file.service.ts depends on 'file-saver'. CommonJS or AMD dependencies can cause optimization bailouts.
38.42 For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
38.42 
38.42 
38.42 
38.42 Error: /app/src/app/layouts/layout-default/layout-default.component.scss exceeded maximum budget. Budget 4.00 kB was not met by 82.16 kB with a total of 86.16 kB.
38.42 
38.42 
------
ui.Dockerfile:12
--------------------
  10 |     COPY vantage6-ui/ /app
  11 |     RUN npm install
  12 | >>> RUN npm run build
  13 |     
  14 |     # run
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
make: *** [Makefile:203: ui-image] Error 1
```
On `main` it seems to build just fine.

Seems to be hitting [this limit](https://github.com/vantage6/vantage6/blob/a734fed7708edd072b08b956f814af38a54344ca/vantage6-ui/angular.json#L40-L42)?

**Comment by frankcorneliusmartin** [comment]
I have only tested in outside of Docker. Maybe good to indeed verify we can actually build it.

**Comment by bartvanb** [comment]
Good that you test building the dockerfile - Frank and I usually don't do this until building release candidates so we would've only found out later. 

In fact, this issue is not due to the changes on this branch, but it also already occurs on `release/4.5`, very likely due to changes in #1214. 

Before increasing the limits, I'm going to try reducing the size of that scss (I think it's big because I'm importing another scss file) - that would be better performance-wise than simply increasing the limits

**Comment by bartvanb** [comment]
I fixed it on this branch by removing the culprit import

**Review by lsago — APPROVED** [review]
Building was a just a way for me to test this – `make` && `docker run` && test :) 

Since Angular is completely outside my wheelhouse, I can't comment much on the code itself :) But, this branch now builds and I tested it and it seems to work nicely!

**Pull request merged**
